import UIKit

extension UIFont {
    static let semiBold32 = FontFamily.Montserrat.semiBold.font(size: 32)
    static let bold27 = FontFamily.Montserrat.bold.font(size: 27)
    static let medium27 = FontFamily.Montserrat.medium.font(size: 27)
    static let semiBold25 = FontFamily.Montserrat.semiBold.font(size: 25)
    static let semiBold14 = FontFamily.Montserrat.semiBold.font(size: 14)
    static let semiBold16 = FontFamily.Montserrat.semiBold.font(size: 16)
    static let semiBold18 = FontFamily.Montserrat.semiBold.font(size: 18)
    static let regular24 = FontFamily.Montserrat.regular.font(size: 24)
    static let medium21 = FontFamily.Montserrat.medium.font(size: 21)
    static let extraBold20 = FontFamily.Montserrat.extraBold.font(size: 20)
    static let bold20 = FontFamily.Montserrat.bold.font(size: 20)
    static let medium18 = FontFamily.Montserrat.medium.font(size: 18)
    static let medium15 = FontFamily.Montserrat.medium.font(size: 15)
    static let medium14 = FontFamily.Montserrat.medium.font(size: 14)
    static let regular14 = FontFamily.Montserrat.regular.font(size: 14)
    static let regular15 = FontFamily.Montserrat.regular.font(size: 15)
    static let regular12 = FontFamily.Montserrat.regular.font(size: 12)
    static let regular10 = FontFamily.Montserrat.regular.font(size: 10)
    static let medium13 = FontFamily.Montserrat.medium.font(size: 13)
    static let medium11 = FontFamily.Montserrat.medium.font(size: 11)
    static let regular11 = FontFamily.Montserrat.regular.font(size: 11)
}
